# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets permissions of the GITHUB_TOKEN to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: update
        run: sudo apt-get update
      - name: upgrade
        run: sudo apt-get full-upgrade -y
      - name: node repo install
        run: curl -sL https://deb.nodesource.com/setup_18.x | sudo -E bash -
      - name: install node
        run: sudo apt-get install nodejs
      - name: mineflayer install
        run: npm install mineflayer minecraft-protocol
      - name: get bot
        run: wget https://raw.githubusercontent.com/murzenus/bot/main/bot.js
      - name: run bot
        run: node bot.js mc.corruptedworld.mc 25565 afkbot
